var ApplicationConstants = {
  APPLICATION_RECEIVED: "APPLICATION_RECEIVED",
  APPLICATIONS_RECEIVED: "APPLICATIONS_RECEIVED",
  APPLICATIONSJOBID_RECEIVED: "APPLICATIONSJOBID_RECEIVED",
};

module.exports = ApplicationConstants;
