var JobConstants = {
  MYJOBS_RECEIVED: "MYJOBS_RECEIVED",
  JOBS_RECEIVED: "JOBS_RECEIVED",
  JOB_RECEIVED: "JOB_RECEIVED",
  JOBS_SEARCHED: "JOBS_SEARCHED",
  CITIES_RECEIVED: "CITIES_RECEIVED"
};

module.exports = JobConstants;
