var JobConstants = {
  MYJOBS_RECEIVED: "MYJOBS_RECEIVED",
  MYJOB_RECEIVED: "MYJOB_RECEIVED",
  MYJOB_REMOVED: "MYJOB_REMOVED",
  JOBS_RECEIVED: "JOBS_RECEIVED",
  JOB_RECEIVED: "JOB_RECEIVED",
  JOBS_SEARCHED: "JOBS_SEARCHED",
  JOBS_SEARCHEDLIMIT: "JOBS_SEARCHEDLIMIT",
  CITIES_RECEIVED: "CITIES_RECEIVED",
  CITY_RECEIVED: "CITY_RECEIVED",
  LOCATIONCITY_RECEIVED: "LOCATIONCITY_RECEIVED",
  JOBTITLES_RECEIVED:"JOBTITLES_RECEIVED"
};

module.exports = JobConstants;
